NCR-Corporation/sample-app-burgers

.github/ISSUE_TEMPLATE/1.Bug_report.md
.github/ISSUE_TEMPLATE/2.Feature_request.md
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md

This pull requests adds Issue Templates and Pull Request templates to the repository. 
1. Visit the fork of this repository at https://github.com/kg185155/sample-app-burgers/issues
2. Click "New Issue"
3. Confirm the issue templates appear.
4. Click on "Bug Report" -> "Get Started"
5. Confirm the Bug Report Issue template markdown is loaded. 
6. Go back and click on "Feature Request" -> "Get Started"
7. Confirm the Feature Report template markdown is loaded
8. Visit an example pull request done on the fork: https://github.com/kg185155/sample-app-burgers/pull/2
9. Confirm the Pull Request template markdown is added (no content was added or edited to showcase the template)
#5

#5 Adding issue templates & pull request templates

---

code/BurgersUnlimited/settings.py
code/BurgersUnlimited/urls.py
code/burger/urls.py
code/static/js/index.js
code/static/js/menu.js
code/templates/addressNotFound.html
code/templates/base.html
code/templates/confirmation.html
code/templates/error.html
code/templates/highlandsMenu.html
code/templates/index.html
code/templates/midtownMenu.html
code/templates/payment.html
code/templates/southlandMenu.html
code/templates/viewCart.html

This PR hides the Login/Logout/Register UI elements from across the site.
It also does some code cleanup and organization:
1. Files have been formatted with `prettier`
2. The `..menu.html` files are now extending `base.html` instead of including the JS and menu every time. This will reduce chances of missing changes made to the header/navigation.
3. Fixing of error on homepage of button on submit function not found
See: https://recordit.co/opi4Mo5Jpf (hopefully that works)
1. Check out this branch and start the site
2. Search for stores
3. Visit each location and confirm filtering, add to cart, etc. still works
4. Visit the cart
5. Confirm adding items, removing items from cart still works
6. Checkout
7. Confirm taken to confirmation screen
8. Visit about page
9. Confirm documentation in …

Removing Login/Logout/Register UI, Code Cleanup

---

code/build/helm/charts/ocpx-ncr-burgers-demo/templates/ocpx-ncr-burgers-demo-deployment.yaml
code/build/helm/charts/ocpx-ncr-burgers-demo/templates/ocpx-ncr-burgers-demo-ingress.yaml

Updating the versions for the helm charts.
I compared this to the self-checkin/hackathon repository templates

Updating Harness Chart Templates

---

README.md

There are some formatting changes but this is mostly adding the Contribution section.

Updating README with contribution guide section

---

README.md

Small change to test develop branch deployment

Testing develop branch

---

code/menuParser.py

Adds the menu parsing file to the repo. This file is responsible for parsing the menu. The is only a piece of the backend update. The app still needs to be updated to connect the new back and front end together but the flow of the site, needs to happen before that can be implemented.
There is nothing to test for this change. The routes of the application were not changed.
MARKET-5092

Adding Menu Parsing File

---

code/static/css/main.css
code/templates/index.html

Adds the open sans font to the text in the homepage and fixes the resulting spacing issus
5066

MARKET-5066: Implement Open Sans in Homepage

---

code/static/js/startsession.js
code/templates/base.html

Fixes the missing picture on the homescreen
5144

MARKET-5144: Fixing the image on the home screen

---

code/static/css/index.css
code/static/css/main.css
code/templates/base.html
code/templates/index.html

Fixes the routing to the image. Should be displayable on the dev environment now.
5144

MARKET-5144: Fixes Image in Nav Bar with Kevin Requested Changes

---

code/static/css/main.css
code/templates/base.html

These are changes at the request of QA.
5144

MARKET-5144: Nav Bar and Footer QA Fixes

---

code/build/cloudbuild/nginx/cloudbuild.yaml
code/build/cloudbuild/pipeline/cloudbuild.yaml

Removing ocpx from cloudbuild pipeline

---

code/build/cloudbuild/pipeline/cloudbuild.yaml

Updating helm to be the latest and not a specific version

---

code/static/css/main.css

resolving missing blue hover color lost during the resolution of merge conflicts.
5144

MARKET-5144 : Nav Bar QA fixes

---

code/build/helm/charts/ncr-burgers-demo-static/templates/ingress/ncr-burgers-demo-static-ingress.yaml

See: https://github.com/NCR-Corporation/ncr-retail-demo/blob/main/build/helm/charts/ncr-retail-demo-static/templates/ingress/ncr-retail-demo-static-ingress.yaml#L24

Updating servicePort in static-ingress

---

code/build/helm/charts/ncr-burgers-demo-static/templates/ingress/ncr-burgers-demo-static-ingress.yaml

This reverts commit 3acb7b297be8ed774ffa0fd3ca71f920703f0bd7.

Revert "Updating servicePort in static-ingress"

---

code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-deployment.yaml

This reverts commit e53baaf013db2215d56fdf4071e812d87b24f8ba, reversing
changes made to 41f88f746a974e21881d19d5af2f838c7e3c6604.
If applicable.
Ticket Number

Revert "Merge pull request #52 from NCR-Corporation/helm-translation"

---

code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-deployment.yaml
code/burger/urls.py
code/burger/views.py

Adding liveliness/readiness probe

---

code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-deployment.yaml

Updating liveness and rediness

---

code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-deployment.yaml

Simpler linenessProbe

---

code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-deployment.yaml

Changing to a TCP probe

---

code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-deployment.yaml

Reverting back to /burger

---

code/build/cloudbuild/nginx/cloudbuild.yaml
code/build/cloudbuild/pipeline/cloudbuild.yaml

Testing adding a suffix to cloudbuild for dev deployments

Adding suffix to cloudbuild

---

code/BurgersUnlimited/settings.py
code/burger/urls.py
code/burger/views.py
code/catalogMaker.py
code/menuParser.py
code/order.py
code/siteMaker.py
code/static/css/footer.css
code/static/css/main.css
code/static/css/menu.css
code/static/js/cartOriginal.js
code/static/js/footer.js
code/static/js/index.js
code/static/js/menuPage.js
code/static/js/startsession.js
code/templates/base.html
code/templates/footer.html
code/templates/index.html
code/templates/itemDetails.html
code/templates/menu.html
code/templates/payment.html

This ticket adds the page where a user can view the different sales items in a menu. All the buttons on the home page should work and the design should be responsive.
Go to the lunch and dinner menu pages and check to see if the design matches the Figma file.
MARKET-5067

MARKET-5067 Implement Lunch & Dinner Pages

---

code/static/css/menu.css
code/templates/menu.html

This pr includes the changes made with the comments made during QA. This includes adding a box-shadow to the menu cards as well as a plus icon to the card's buttons.
MARKET-5067

MARKET-5067: Implement Lunch & Dinner Menu Pages

---

code/BurgersUnlimited/settings.py
code/HMACAuth.py
code/templates/base.html
code/templates/index.html

1.) I have eliminated any unnecessary variables in the settings.py since we only need nep-org, secret, and shared key for hmac authorization. I have also removed any references to the deleted variables in the HMACAuth.py file as to not cause any issues.
2.) Another change that wasn't caught in QA yet is the Start your Order button doesn't go anywhere! I have since fixed this button to go to the appropriate restaurant's menu at the appropriate time.
3.) I also removed a weird grey border effect that the change location button had. The screenshots show a respective before and after
5067

MARKET-5067: Implement Lunch and Dinner Pages

---

code/auxMethods.py
code/burger/views.py
code/menuParser.py
code/order.py
code/static/css/menu.css

This fix includes some spacing issues on larger screens in regards to the cards being shown
5285

MARKET-5285: Recreate Catalog Menus

---

code/static/css/index.css
code/templates/index.html

This ticket changes the structure of the homepage around so that it is more pleasant design-wise than the previous iteration. Text should be visible and readable and appropriate spacing between items should be handled
5208

MARKET-5208: Homepage Responsiveness Redesign

---

code/BurgersUnlimited/settings.py
code/HMACAuth.py
code/burger/views.py
code/menuParser.py
code/static/css/itemDetails.css
code/static/js/cart.js
code/static/js/itemDetails.js
code/static/js/menu.js
code/static/js/startsession.js
code/templates/base.html
code/templates/index.html
code/templates/itemDetails.html

This page implements the frontend design detailed in the figma page. 
🐈- Demo Kitty
🔍 -Figma Standard
https://www.figma.com/file/TdRUGgwZVKWD1vxizIrDJA/Hospitality-Sample-App?node-id=317%3A927
1.) Start the Application on the Staging Environment
2.) Pick any site in the location modal
3.) Navigate to the dinner or lunch menu
4.) Pick a burger
5.) Add and remove toppings from the burger
6.) Add the item to the order {Ensure a modal pops up}
7.) Test checking out and continue ordering buttons
_The demo headings for the toppings differs slightly from the figma file. I was told that this was fine._ 
_I will add this in tomorrow 👍🏾_

TM185221 & KG185155- Frontend Modifiers Page

---

code/static/js/confirmation.js
code/templates/confirmation.html

Made the text larger in the finish line container and made the 'get started' button link to the getting started section of developer.ncr.com.
MARKET-5294

MARKET-5294: Implement Finish Line Page QA Comments

---

README.md
code/requirements.txt

This PR updates the README to reflect the changes to the Hospitality Sample App as well as eliminates any unnecessary installations that aren't needed to execute the app
MARKET-5438

MARKET-5438: Update README.md

---

code/static/js/cart.js
code/templates/base.html

This ticket just provides a bit of cleanup to the sample app before it gets sent to QA for End-To-End Testing. 
MARKET-5422

MARKET-5422: End-To-End Testing

---

code/requirements.txt

MARKET-5422: Add Gunicorn Back 

---

code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-deployment.yaml
code/build/helm/charts/ncr-burgers-demo-app/values.yaml
code/build/helm/charts/ncr-burgers-demo-static/values.yaml

MARKET-5422 Update charts

---

code/build/helm/charts/ncr-burgers-demo-app/Chart.yaml
code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-deployment.yaml
code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-scaler.yaml
code/build/helm/charts/ncr-burgers-demo-app/values.yaml
code/build/helm/charts/ncr-burgers-demo-static/Chart.yaml
code/build/helm/charts/ncr-burgers-demo-static/templates/ingress/ncr-burgers-demo-static-ingress.yaml
code/build/helm/charts/ncr-burgers-demo-static/templates/services/ncr-burgers-demo-static-service.yaml
code/build/helm/charts/ncr-burgers-demo-static/values.yaml

MARKET-5422 More helm chart cleanup

---

code/BurgersUnlimited/settings.py
code/Dockerfile

fixed docker file to include the migrate command and removed the secret key that doesn't need to be exposed
If applicable.
Ticket Number

MARKET-5422: Merge to Main

---

code/Dockerfile
code/build/cloudbuild/django/gunicorn-start.sh

MARKET-5418; Merge to Main

---

code/build/cloudbuild/django/docker-startup.sh
code/build/cloudbuild/django/gunicorn-start.sh
code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-deployment.yaml

MARKET-5422: Merge Develop with Main

---

code/build/helm/charts/ncr-burgers-demo-static/templates/ingress/ncr-burgers-demo-static-ingress.yaml

MARKET-5422: Update Develop Ingress

---

code/build/helm/charts/ncr-burgers-demo-static/templates/ingress/ncr-burgers-demo-static-ingress.yaml

MARKET-5422: Fix Harness Pipeline

---

code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-scaler.yaml
code/build/helm/charts/ncr-burgers-demo-static/templates/backend/ncr-burgers-demo-static-backend-config.yaml
code/build/helm/charts/ncr-burgers-demo-static/templates/services/ncr-burgers-demo-static-service.yaml

MARKET-5422 Ditch beta

---

code/build/cloudbuild/django/docker-startup.sh
code/build/helm/charts/ncr-burgers-demo-app/templates/ncr-burgers-demo-app-deployment.yaml
code/build/helm/charts/ncr-burgers-demo-app/values.yaml
code/docker-compose.yml

MARKET-5422 Substitute SECRET_KEY

---

__version__.py

Please include a description of what this pull request does or what it is trying to solve. This pull requests fixes XYZ or implements adding version file for automation

adding __version__.py file

---

code/static/js/itemDetails.js
code/templates/itemDetails.html

- commenting out the recent code to see if this is the cause of the 500 error

MARKET-7001-comment out code to test

---

code/static/js/menuPage.js

adding console log for testing

MARKET-7001-update-menu-page

---

code/static/js/menuPage.js

MARKET-7001-debugging

---

code/BurgersUnlimited/settings.py

MARKET-7001-adding white noise

---

code/BurgersUnlimited/settings.py
code/build/cloudbuild/django/gunicorn-start.sh
code/requirements.txt

MARKET-7001-fix-error

---

code/BurgersUnlimited/settings.py
code/build/cloudbuild/django/docker-startup.sh

MARKET-7001-fixing

---

code/static/js/itemDetails.js
code/static/js/menuPage.js
code/templates/itemDetails.html

reverting all the changes that i made to put the code back into old state

MARKET-7001-reverting-back-to-old-state

---

code/build/cloudbuild/django/docker-startup.sh

MARKET-7068-setting debug to true

---

code/burger/views.py
code/static/js/itemDetails.js

MARKET-7068-adding print for logging

---

code/build/cloudbuild/django/docker-startup.sh
code/burger/views.py

adding print and removing location in docker

MARKET-7068-adding print and removing location in docker startup

---

code/burger/views.py

adding session save and more prints

MARKET-7068-adding more prints and session save

---

code/burger/views.py

adding modified to true and printing location

MARKET-7068-adding modified to true and printing location

---

code/burger/views.py

MARKET-7068-adding cookie

---

code/BurgersUnlimited/settings.py

adding SESSION_SAVE_EVERY_REQUEST and SESSION_COOKIE_PATH

MARKET-7068-adding seesion save every request

---

code/BurgersUnlimited/settings.py

MARKET-7068-adding seesion-engine

---

code/BurgersUnlimited/settings.py
code/burger/views.py

adding secure proxy ssl header and session cookie secure

MARKET-7068-adding secure proxy ssl header and session cookie secure

---

code/BurgersUnlimited/settings.py

MARKET-7068-adding dummy cache

---

code/Dockerfile

adding apk add sqlite3

---

code/Dockerfile

adding code
RUN apt-get update && \
apt-get install -y sqlite3

updating docker
